#!/usr/bin/env python3
"""
Script to create a complete resume.json with ALL projects from menu.json
"""

import json
import os
import re

def strip_html_tags(text):
    """Remove HTML tags from text"""
    if not text:
        return ""
    # Remove HTML tags
    clean = re.compile('<.*?>')
    text = re.sub(clean, '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def create_concise_summary(project_data):
    """Create a concise one-paragraph summary for a project"""
    
    # Define concise summaries for each project
    summaries = {
        "carnegie-mellon-university": "Led the complete redesign and implementation of Carnegie Mellon University's flagship website and distributed CMS ecosystem, managing an 18-month project that modernized the university's digital presence across 50+ departments. Built a scalable component-based architecture using Drupal, GitLab, and Pantheon Upstream that supports both the main CMU.edu site and multiple unit sites while maintaining brand consistency. Implemented 50+ reusable components, distributed content management workflows, and enterprise integrations including LiveWhale events, faculty directories, and program finders. The system achieved WCAG 2.1 AA accessibility compliance, mobile-first responsive design, and enabled autonomous content management for individual units while reducing development time for new sites by 60%.",
        
        "clarkson-university": "Implemented a comprehensive Drupal 9 website redesign for Clarkson University on Pantheon, collaborating with Carnegie Higher Ed for design strategy. Built a modern, accessible platform featuring PeopleSoft integration for dynamic faculty directories, Funnelback search capabilities, and modular content management using Drupal Paragraphs. Developed custom modules for emergency alerts, EMS calendar integration, and microsite functionality. Achieved WCAG 2.1 AA accessibility compliance with automated monitoring tools and created a sustainable CMS that enables distributed editors to build flexible pages without developer assistance.",
        
        "yale-center-for-british-art": "Designed and implemented a dual-platform digital ecosystem for Yale Center for British Art, comprising a Drupal 10 museum website and a headless Drupal 11 collections search backed by Apache Solr. Built a comprehensive content architecture supporting 2,000+ paintings, 250 sculptures, and 40,000+ library items with faceted search capabilities. Implemented WCAG 2.0 Level AA compliance, editorial workflows, and third-party integrations including Bedework events and Google Places API. Created a custom remote Solr integration module for the Drupal community and established a scalable foundation for future growth.",
        
        "fox-chase-cancer-research": "Led the complete website redesign and Drupal implementation for Fox Chase Cancer Center, partnering with Transit Authority Figures for design strategy. Built a patient-centric platform featuring modular content management using Drupal Paragraphs, advanced search functionality with Google Search Appliance integration, and comprehensive accessibility features meeting Temple University's ADA guidelines. Implemented custom modules for faculty and scientist directories, emergency alert systems, and third-party integrations including YouTube, Google Maps, and clinical trial forms. Created a responsive, accessible design that serves patients, researchers, and donors effectively.",
        
        "kettering-university": "Executed a comprehensive Drupal 10 upgrade and component-based redesign for Kettering University, implementing a four-phase strategy that modernized the institution's digital presence. Built flexible templates for academic programs, faculty directories, and student resources while integrating external data sources for program information and social media feeds. Developed a program finder with filtering capabilities and implemented accessibility compliance with WCAG guidelines. Created a scalable architecture that supports the university's focus on advanced mobility, new energy vehicles, and intelligent manufacturing while maintaining brand consistency across all digital touchpoints.",
        
        "la-jolla-country-day-school": "Collaborated with Verso Design to build a Drupal website that reflects La Jolla Country Day School's mission of nurturing well-rounded learners. Structured the information architecture around the school's three divisions and implemented custom content types for academics, arts, athletics, and community service. Created a warm, welcoming visual identity with purpose-driven messaging that celebrates independent thinking. Integrated customizable event calendars, faculty directories, and admission inquiry forms to provide prospective families with clear pathways to learn about the IB program and schedule campus visits.",
        
        "lewis-katz-school-of-medicine-temple-university": "Implemented a modern Drupal website for Temple University's Lewis Katz School of Medicine, partnering with Transit Authority Figures for design and user experience strategy. Built a responsive platform featuring dynamic homepage slideshows, flexible content management using Drupal Paragraphs, and a sophisticated faculty directory with predictive search capabilities. Implemented comprehensive accessibility features including relative font sizes, alt-text enforcement, and keyboard navigation to meet Temple's Web Accessibility Standards. Integrated third-party services including Google Custom Search, events feeds, and social sharing tools to create an engaging digital experience for prospective students and researchers.",
        
        "lim-college": "Executed a strategic website refresh for LIM College, translating Carnegie Higher Ed's creative vision into a functional Drupal 9 platform without rebuilding the entire system. Built new templates for homepage, program finder, and program pages while preserving existing infrastructure and content. Implemented embedded RFI forms, updated design system components, and enhanced accessibility by replacing tabbed interfaces with accordions. Created a program finder with filters for degree level, modality, area of study, and career field, and improved mobile performance to address the high share of mobile sessions. Established a foundation for continuous improvement through analytics-informed refinements.",
        
        "madison-country-day-school": "Collaborated with Verso Design to create a Drupal website that captures Madison Country Day School's commitment to challenge and support as an International Baccalaureate World School. Implemented a versatile page builder using Drupal Paragraphs enabling teachers and administrators to craft pages for the IB curriculum, arts, athletics, and admissions. Created an inviting visual identity and messaging that celebrates student curiosity while integrating event calendars, news blogs, and parent portals. Provided prospective families with clear pathways to learn about the IB program and schedule campus visits while offering current families secure access to resources.",
        
        "mit": "Built a sophisticated Drupal platform for MIT Solve that serves as a digital innovation lab connecting entrepreneurs, researchers, and change-makers globally. Created a matchmaking service that enables challenge-seekers to connect with solution-builders and big ideas with resources needed to become reality. Implemented features for showcasing global challenges, collaborative solution development, and pathways for supporters and investors to discover and fund promising initiatives. Designed a user experience that serves everyone from Nobel laureates to startup founders without overwhelming any audience, handling everything from initial ideation to ongoing project management and impact tracking.",
        
        "northeastern-illinois-university": "Designed and implemented a Drupal website for Northeastern Illinois University that celebrates the institution's diversity and accessibility, collaborating with Carnegie Higher Ed for design direction and content strategy. Built custom program pages showcasing academic offerings alongside student testimonials and success metrics, and created an interactive campus map helping prospective students explore the university's four Chicago locations. Implemented ADA-compliant design, built multilingual capability to serve NEIU's diverse community, and integrated application portals and event calendars. Created a user-friendly site that positions NEIU as an inclusive institution dedicated to student success.",
        
        "university-of-massachusetts-amherst": "Built a Drupal distribution for UMass Amherst College of Humanities and Fine Arts that serves more than 20 departments while maintaining consistent branding across the college. Created a platform allowing each department to launch its own site with the same design framework, including pre-made content types and taxonomies for academic programs, faculty bios, and events. Implemented a Blocks Placer interface enabling editors to position and customize blocks such as slideshows and accent colors. Designed a rotating footer background and moving logo to create visual interest while reinforcing the college's identity. Reduced duplication of effort by enabling content sharing across departments while allowing each department to highlight unique offerings.",
        
        "massachusetts-municipal-wholesale-electric-company": "Developed a comprehensive member portal and NextZero rebate application for MMWEC, a not-for-profit public corporation serving 23 municipal light departments. Built a secure, scalable Drupal platform that streamlines communication and collaboration for municipal utilities while helping them meet clean-energy mandates. Implemented advanced portal functionality including user authentication, document management, and rebate processing workflows. Created a robust system that supports the agency's mission of providing power-supply, financial, and risk-management services to member utilities across Massachusetts.",
        
        "ab_inbev": "Designed and implemented a scalable B2B ordering portal for AB InBev's wholesale distribution model in Latin America and beyond. Built a multilingual, multi-brand environment using Magento Enterprise Edition with Docker containerization for rapid deployment across multiple countries. Implemented custom AB API adapters, multi-country logic, and Mulesoft API integration for real-time communications with country-specific backend systems. Created a user-friendly interface emphasizing simplicity for B2B users with tiled visual browsing and mobile-friendly filtering. Established a scalable foundation supporting future growth while reducing order friction and improving rebate application tracking.",
        
        "smartlabs": "Built a comprehensive three-tier digital ecosystem for SmartLabs spanning public marketing, secure member operations, and specialized compliance management. Implemented a modern marketing site, multi-tenant member portal on Drupal 8, and specialized vivarium compliance platform with enterprise-grade security. Created sophisticated badge management systems with enforced company-specific quotas, integrated third-party tools including BioRAFT, TEEM, and Zendesk, and implemented SSO authentication through company identity providers. Built a scalable architecture supporting rapid expansion across Boston, Cambridge, and San Francisco while maintaining operational reliability and regulatory compliance.",
        
        "carv-resource-management": "Developed Carv.io, a resource management platform that transforms time tracking into true capacity forecasting for small and mid-sized teams. Built two working prototypes: a browser-based pipeline simulator and a curved (Bezier) hours allocator that model project dynamics beyond simple record-keeping. Implemented confidence zones (25%, 50%, 75%, 100%) to handle uncertainty in project pipelines and created a quadratic Bezier curve system for realistic effort distribution across timelines. Designed a systems-theory approach that models flow, entry, attrition, and maturation while making uncertainty visible. Created a foundation for future recommendation engines using statistical methods and machine learning informed by real time-log data.",
        
        "glassica-app": "Prototyped a hexagon-based puzzle game through three iterations: an iOS puzzle app, a two-player p5.js game, and a physical laser-cut board. Built an iOS game featuring polyiamond shape placement, color mixing mechanics, and rotating concentric rings with snap-to-grid functionality. Created a two-player competitive game similar to Go using the same hexagonal board mechanics with territory control and capture rules. Designed and fabricated a physical prototype using Ponoko's laser-cutting service with precise tolerances for smooth rotation. Demonstrated how a single mechanic—rotating concentric hexagonal rings—can support both casual puzzles and competitive territory games across digital and physical media.",
        
        "music-app-experiments": "Developed three complementary web-based music generation tools: Jazz Hero, Strudelizer, and Musical Call & Response. Built Jazz Hero as a headless Django REST API with Angular frontend for jazz practice, featuring customizable chord progressions and melodic line generation. Created Strudelizer to bridge hardware performance and live coding by translating MIDI input into Strudel syntax in real-time. Implemented Musical Call & Response combining Tone.js synthesis with Magenta MusicRNN for AI-powered musical conversations. Designed cross-cultural scale systems including Western modes and Indian ragas, demonstrating how browser technologies can democratize music creation and learning.",
        
        "choosroozy": "Built ChoozRoozy, a visual decision-making tool that transforms abstract choice criteria into draggable, manipulable elements on a digital canvas. Implemented a transparent algorithm where each factor becomes a weighted circle that users can position and resize to reflect importance and directional preference. Created an intuitive interface using p5.js for smooth interactions without technical overhead, allowing users to rename options, customize factors, and export decision snapshots. Designed the tool to prompt reflection rather than mystify outcomes, helping users understand their priorities and reclaim agency in decision-making processes.",
        
        "paragraphs-stats-module": "Developed Paragraphs Stats, an open-source Drupal module that provides content managers and designers with comprehensive visibility into how Paragraphs components are utilized across Drupal sites. Built a utilization matrix showing every paragraph type against every content type with color-coded usage levels and drill-down reports. Implemented metadata tracking, CSV export functionality, and automated scanning of entity bundles and fields. Created a solution that enables data-driven decisions about component libraries, helping teams identify unused components, measure adoption of new features, and maintain lean, performant websites. Contributed the module to the Drupal community to improve content governance across the ecosystem.",
        
        "aier-american-institute-for-economic-research": "Executed a comprehensive Drupal 7 migration and redesign for the American Institute for Economic Research, the oldest economic research institute in the United States. Consolidated multiple content types into six core types while implementing advanced taxonomy systems for research categories, educational classifications, and archive organization. Built responsive design with mobile-first approach, infinite scroll functionality, and comprehensive third-party integrations including Authorize.net for e-commerce and NetworkforGood for donations. Implemented accessibility features including relative font sizes, alt-text enforcement, and keyboard navigation. Created a modern platform that serves AIER's diverse content needs while maintaining their prestigious position in economic research.",
        
        "smma-architecture": "Collaborated with design agency Toky to deliver a comprehensive website redesign and CMS implementation for SMMA Architecture using WordPress and Elementor. Built a visually compelling platform featuring render-to-reality blocks, dynamic media galleries, and interactive storytelling components. Implemented Advanced Custom Fields for precise content structuring, HubSpot integration for streamlined marketing workflows, and Tinify API for automated image compression. Created responsive design with sophisticated animations and integrated social media feeds using SmashBalloon. Built a robust, user-friendly platform that captures SMMA's innovative design solutions while providing flexible content management capabilities.",
        
        "monadnock-media": "Built a headless CMS architecture for Monadnock Media using Strapi as the content management foundation and implemented advanced front-end development with sophisticated animations and interactions. Created a modern, engaging website that supports the organization's journalism mission with scroll-triggered effects, quasi-3D layering, and interactive elements. Implemented modular structure for maintainability, integrated third-party services, and optimized performance through lazy loading and responsive design. Built a platform that serves both practical needs of a local newspaper and provides an engaging, modern user experience that helps the publication stand out in the digital media landscape.",
        
        "robert-rauschenberg-foundation": "Executed a comprehensive Drupal 7 to Drupal 10 migration for the Robert Rauschenberg Foundation, modernizing their complex platform with thousands of artwork records and archive entries. Consolidated multiple content types into a streamlined system using Drupal 10's Layout Builder to empower non-technical editors with drag-and-drop page construction. Implemented FileMaker integration using the Feeds FileMaker Module for automated import of art and archive records while maintaining data integrity and curatorial flexibility. Built advanced search and filtering capabilities, combined mapping functionality for on-view and public collections, and created an interactive timeline for the artist's chronology. Delivered a more intuitive user experience while positioning the Foundation's digital presence to support their mission of promoting Rauschenberg's artistic and philanthropic legacy.",
        
        "jack-daniels": "Collaborated with Arnold Worldwide to build a global website for Jack Daniels that showcases the brand's heritage and craftsmanship while providing an engaging digital experience for consumers worldwide. Implemented a sophisticated content management system that supports multiple markets and languages while maintaining brand consistency. Built interactive features including virtual tours, product showcases, and storytelling elements that bring the brand's history to life. Created a responsive design that works seamlessly across all devices and integrated analytics to track user engagement and brand performance. Delivered a platform that strengthens Jack Daniels' position as a premium spirits brand while providing valuable insights for marketing and brand development.",
        
        "studio-arts-consortium-international-saci-florence": "Designed and implemented a comprehensive Drupal website for Studio Arts College International (SACI) in Florence, Italy, collaborating with Stoltze Design for visual identity and user experience. Built a responsive platform featuring extensive content architecture supporting programs, courses, faculty, events, and student galleries with advanced taxonomy systems. Implemented custom content types for programs, courses, faculty/alumni, events, and student galleries with dynamic filtering and search capabilities. Created a full-page scroll experience with hero media, promoted programs, news grids, and event carousels. Integrated third-party services including YouTube/Vimeo video hosting, Google Analytics, and ShareThis for social sharing. Delivered a modern digital presence that reflects SACI's blend of Renaissance tradition and contemporary art education while improving accessibility and enrollment.",
        
        "the-isabella-stewart-gardner-museum": "Designed and implemented a sophisticated Drupal 8 digital platform for the Isabella Stewart Gardner Museum, partnering with Fabrique for design strategy. Built a comprehensive content management system integrating Embark Collections data for over 2,500 art objects with real-time XML synchronization. Created custom content types for stories, events, exhibitions, and room experiences with interactive audio player integration via LibSyn. Implemented advanced filtering and search capabilities across all content types with dynamic room mapping and wayfinding features. Built multi-media story chapters with before/after sliders, video, and audio components supporting up to 15 interactive chapters per story. Delivered a responsive, accessible platform that honors the museum's unique character while providing modern functionality for diverse user needs.",
        
        "way-finders": "Built a comprehensive multi-site Drupal platform for Way Finders supporting their organizational rebrand and three distinct business lines: Housing Center, Real Estate Development, and Community Engagement. Implemented an innovative architecture presenting four distinct site sections while maintaining a unified codebase, template system, and taxonomy structure. Created custom content types for properties, team directories, resource centers, and news/impact materials with advanced filtering capabilities. Integrated multiple third-party systems including Newton Software for careers, Eventbrite for events, Blackbaud/eTapestry for donations, and GoSection8 for housing search. Implemented Google Translate integration for 9 languages and created a dynamic navigation system with contextual logo changes and collapsible menus. Delivered a sophisticated digital ecosystem that effectively communicates Way Finders' multi-faceted mission while supporting complex operational requirements.",
        
        "chemex-coffee-maker": "Built a comprehensive Shopify e-commerce platform for Chemex Corporation showcasing their iconic coffee brewing products and reinforcing the brand's heritage. Implemented extensive product catalog navigation with categories for Classic Series, Glass Handle, Handblown, and electric units with bundled products and subscription filter packs. Created an educational hub with step-by-step brewing guides, videos, and filter-folding instructions to help visitors learn brewing techniques. Developed a quiz-style recommendation tool to help customers choose the appropriate coffeemaker size and series. Integrated newsletter sign-ups, wholesale applications, and discount banners with Shopify's subscription APIs for auto-ship functionality. Delivered a responsive design that evokes the brand's minimalist aesthetic while ensuring seamless mobile shopping experience.",
        
        "guardair": "Designed and implemented a comprehensive Shopify e-commerce platform for Guardair Corporation, a leading manufacturer of safety air guns and pneumatic tools. Built an extensive product catalog featuring safety air guns, air nozzles, air knives, air amplifiers, and pneumatic tools with detailed product specifications and safety information. Created educational content including safety guidelines, application guides, and technical resources to help customers understand proper air tool usage. Implemented advanced filtering and search capabilities allowing customers to find products by application, industry, or technical specifications. Integrated customer account management, order tracking, and technical support request forms. Delivered a professional, user-friendly platform that reflects Guardair's commitment to safety and quality while providing comprehensive product information and easy purchasing.",
        
        "pioneer-valley-books": "Built a comprehensive Shopify e-commerce platform for Pioneer Valley Books, a leading educational publisher specializing in leveled reading materials for K-12 students. Implemented an extensive product catalog featuring leveled books, guided reading sets, and educational resources with advanced filtering by reading level, grade, and subject matter. Created educational content including reading level guides, teaching resources, and professional development materials to support educators. Developed a robust search and filtering system allowing teachers and administrators to find appropriate materials for their students. Integrated customer account management with educational institution verification and bulk ordering capabilities. Implemented a responsive design optimized for educators browsing on various devices. Delivered a platform that supports Pioneer Valley Books' mission of providing high-quality educational materials while making it easy for educators to find and purchase appropriate resources.",
        
        "sleep-studio": "Designed and implemented a comprehensive Shopify e-commerce platform for Sleep Studio, a company focused on helping people achieve deep, restorative sleep through innovative sleep solutions. Built an extensive product catalog featuring sleep tracking devices, smart mattresses, sleep accessories, and wellness products with detailed product information and sleep science content. Created educational content including sleep tips, research articles, and personalized sleep recommendations to help customers improve their sleep quality. Implemented a sleep assessment quiz to help customers find the right products for their specific sleep needs. Integrated customer account management with sleep tracking data visualization and personalized recommendations. Developed a responsive design optimized for customers researching sleep solutions on various devices. Delivered a platform that supports Sleep Studio's mission of harnessing the power of sleep while providing comprehensive product information and personalized recommendations.",
        
        "sparx-hockey": "Built a comprehensive Shopify e-commerce platform for Sparx Hockey, a manufacturer of automated skate-sharpening equipment for ice hockey, figure skating, and sled hockey. Implemented an extensive product catalog featuring skate sharpeners, accessories, and maintenance equipment with detailed technical specifications and usage instructions. Created educational content including sharpening guides, maintenance tutorials, and equipment care instructions to help customers maintain their equipment properly. Developed a robust search and filtering system allowing customers to find products by sport, skill level, or equipment type. Integrated customer account management with equipment registration and warranty tracking. Implemented a responsive design optimized for customers researching equipment on various devices. Delivered a platform that supports Sparx Hockey's mission of providing professional-grade equipment while making it easy for customers to find and purchase the right products for their needs.",
        
        "trillium-brewing": "Designed and implemented a comprehensive Shopify e-commerce platform for Trillium Brewing Company, a craft brewery known for their artisanal beers and lifestyle-focused brand. Built an extensive product catalog featuring their beer lineup, merchandise, and brewery accessories with detailed product descriptions and brewing information. Created educational content including beer style guides, brewing process information, and food pairing recommendations to enhance customer experience. Implemented advanced filtering and search capabilities allowing customers to find products by beer style, alcohol content, or seasonal availability. Integrated customer account management with age verification and local delivery options. Developed a responsive design that reflects Trillium's artisanal brand aesthetic while providing easy online ordering. Delivered a platform that supports Trillium's mission of creating a lifestyle centered on artisanal beer while providing comprehensive product information and seamless purchasing experience.",
        
        "lanshin": "Built a comprehensive Shopify e-commerce platform for Lanshin, a company specializing in traditional Chinese medicine and wellness products. Implemented an extensive product catalog featuring herbal supplements, wellness tools, and educational materials with detailed product information and traditional medicine content. Created educational content including wellness guides, traditional medicine information, and personalized health recommendations to help customers understand their products. Developed a robust search and filtering system allowing customers to find products by health concern, traditional use, or product type. Integrated customer account management with health profile tracking and personalized recommendations. Implemented a responsive design optimized for customers researching wellness solutions on various devices. Delivered a platform that supports Lanshin's mission of providing traditional Chinese medicine solutions while making it easy for customers to find and purchase appropriate products.",
        
        "p5-projects": "Developed a series of generative art sketches using p5.js to explore creative coding and algorithmic art generation. Built interactive sketches that demonstrate various generative techniques including particle systems, procedural geometry, and mathematical pattern generation. Created responsive designs that adapt to different screen sizes and user interactions. Implemented real-time parameter controls allowing users to adjust generative algorithms and see immediate visual feedback. Developed a collection of sketches showcasing different artistic styles and mathematical concepts. Delivered a portfolio of generative art pieces that demonstrate creative coding skills and artistic vision while providing engaging interactive experiences for viewers.",
        
        "pen-plotting-works": "Developed a creative coding project that bridges digital and physical art by converting p5.js Bézier curve sketches into pen plotter artwork. Built a p5.js sketch that generates complex Bézier curve patterns with interactive controls for curve manipulation and pattern generation. Implemented export functionality that converts digital sketches into vector formats suitable for pen plotters and laser cutters. Created a workflow that allows for iterative design refinement between digital and physical mediums. Developed documentation and tutorials explaining the process of moving from digital sketches to physical artwork. Delivered a complete system that demonstrates the intersection of creative coding, digital fabrication, and artistic expression while providing practical tools for artists and makers.",
        
        "sculpture-works": "Curated and designed a digital exhibition showcasing Chris Amato's first solo exhibition 'Experiments in Material and Flow' featuring sculpture works and material explorations. Built an interactive digital gallery that presents the exhibition's themes of material experimentation and artistic process. Created detailed documentation of individual artworks with high-resolution photography and artist statements. Implemented a responsive design that adapts to different viewing contexts and device types. Developed educational content explaining the artistic concepts and material processes behind the works. Delivered a comprehensive digital exhibition that extends the physical show's reach while providing engaging documentation of the artistic process and material explorations.",
        
        "thing-y": "Developed Thing Y, an innovative toy concept that bridges digital and physical play experiences. Built a prototype that combines traditional toy elements with modern interactive features and educational content. Created a comprehensive design system including product specifications, user experience guidelines, and manufacturing considerations. Implemented digital companion features that enhance the physical toy experience through apps and online content. Developed marketing materials and educational content explaining the toy's unique features and benefits. Delivered a complete product concept that demonstrates innovation in toy design while providing engaging play experiences for children.",
        
        "vases": "Designed and produced 'Test Tube Babies,' a distinctive series of bud vases that combine functional design with artistic expression. Created a collection of vases inspired by laboratory glassware and scientific aesthetics while maintaining practical functionality. Built a comprehensive design system including multiple vase forms, material specifications, and production processes. Implemented quality control measures ensuring each vase meets both aesthetic and functional requirements. Developed marketing materials and product photography showcasing the unique design aesthetic. Delivered a complete product line that demonstrates the intersection of art, design, and functionality while providing beautiful and practical home decor items.",
        
        "dog-door": "Designed and developed an innovative smart dog door solution that combines traditional pet door functionality with modern technology and aesthetic design. Built a prototype that addresses common issues with commercial pet doors including security, weather protection, and visual appeal. Created a comprehensive design system including mechanical components, electronic controls, and aesthetic considerations. Implemented smart features including access control, activity monitoring, and integration with home automation systems. Developed user-friendly controls and mobile app interface for easy management. Delivered a complete product concept that solves real problems for pet owners while providing modern, attractive design that integrates seamlessly with home aesthetics."
    }
    
    slug = project_data.get("slug", "")
    return summaries.get(slug, "Project summary not available.")

def process_menu_data(menu_data):
    """Process the menu data and create concise summaries for ALL projects"""
    
    for item in menu_data:
        if "submenu" in item:
            for subitem in item["submenu"]:
                if "pageSummary" in subitem:
                    # Always replace with concise summary to ensure consistency
                    subitem["pageSummary"] = create_concise_summary(subitem)
    
    return menu_data

def main():
    # Read the original menu.json file
    with open("data/menu.json", "r", encoding="utf-8") as f:
        menu_data = json.load(f)
    
    # Process the data to create concise summaries for ALL projects
    resume_data = process_menu_data(menu_data)
    
    # Write the processed data to resume.json
    with open("resume/resume.json", "w", encoding="utf-8") as f:
        json.dump(resume_data, f, indent=2, ensure_ascii=False)
    
    print("Successfully created resume/resume.json with ALL projects and concise summaries")

if __name__ == "__main__":
    main() 